[mypy]
ignore_missing_imports = True
disallow_untyped_defs = False
check_untyped_defs = False
disable_error_code = import-untyped, index, union-attr, arg-type, call-overload, return-value, attr-defined
